default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: <%= ENV['BLOOG_DATABASE'] %>
  username: <%= ENV['BLOOG_DATABASE_USERNAME'] %>
  password: <%= ENV['BLOOG_DATABASE_PASSWORD'] %>
  host: <%= ENV['BLOOG_HOST'] %>
  port: 5432
  url: <%= ENV['BLOOG_DATABASE_URL'] %>

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice
  
test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: <%= ENV['BLOOG_DATABASE'] %>
  username: <%= ENV['BLOOG_DATABASE_USERNAME'] %>
  password: <%= ENV['BLOOG_DATABASE_PASSWORD'] %>
  port: 5432
  url: <%= ENV['BLOOG_DATABASE_URL'] %>
